version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 test_app.wsgi:application"
    volumes:
      - .:/app
      - static_data:/app/static
    ports:
      - "8000:8000"

volumes:
  static_data: