version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 test_app.wsgi:application"
    volumes:
      - .:/app
      - static_data:/app/static
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - static_data:/var/www/html/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static_data:
